### ISSUE TITLE
Syntax error in main.py

### ISSUE THREAD

**Issue by kimllee** [Hacksore/bt-hid-proxy#2]
Hello,

There was 2 errors in the python script. I have fixed one but can't fix the other one. 
Tested on rpi zero 2 w under pi OS : 20211203
Thank you :)

**Fixed**

pi@raspberrypi:~ $ sudo systemctl status bt-hid-proxy.service -l
● bt-hid-proxy.service - BT HID PROXY
     Loaded: loaded (/etc/systemd/system/bt-hid-proxy.service; enabled; vendor preset: enabled)
     Active: activating (start) since Mon 2022-01-03 18:53:19 GMT; 20ms ago
   Main PID: 1808 (python)
      Tasks: 1 (limit: 409)
        CPU: 1ms
     CGroup: /system.slice/bt-hid-proxy.service
             └─1808 /usr/bin/python /home/pi/bt-hid-proxy/app/main.py

Jan 03 18:53:20 raspberrypi python[1809]:           ^
Jan 03 18:53:20 raspberrypi python[1809]: SyntaxError: Missing parentheses in call to 'print'. Did you>Jan 03 18:53:20 raspberrypi systemd[1]: bt-hid-proxy.service: Main process exited, code=exited, status>Jan 03 18:53:20 raspberrypi systemd[1]: bt-hid-proxy.service: Failed with result 'exit-code'.
Jan 03 18:53:20 raspberrypi systemd[1]: Failed to start BT HID PROXY.
Jan 03 18:53:20 raspberrypi systemd[1]: bt-hid-proxy.service: Scheduled restart job, restart counter i>Jan 03 18:53:20 raspberrypi systemd[1]: Stopped BT HID PROXY.
Jan 03 18:53:20 raspberrypi systemd[1]: Starting BT HID PROXY...
Jan 03 18:53:20 raspberrypi python[1810]:   File "/home/pi/bt-hid-proxy/app/main.py", line 69
Jan 03 18:53:20 raspberrypi python[1810]:     print "No keyboard - waiting..."
Jan 03 18:53:20 raspberrypi python[1810]:           ^

**Not fixed**
pi@raspberrypi:~ $ sudo systemctl status bt-hid-proxy.service -l
● bt-hid-proxy.service - BT HID PROXY
     Loaded: loaded (/etc/systemd/system/bt-hid-proxy.service; enabled; vendor preset: enabled)
     Active: activating (start) since Mon 2022-01-03 18:55:49 GMT; 110ms ago
   Main PID: 2447 (python)
      Tasks: 1 (limit: 409)
        CPU: 96ms
     CGroup: /system.slice/bt-hid-proxy.service
             └─2447 /usr/bin/python /home/pi/bt-hid-proxy/app/main.py

Jan 03 18:55:49 raspberrypi systemd[1]: Starting BT HID PROXY...
Jan 03 18:55:49 raspberrypi python[2447]:   File "/home/pi/bt-hid-proxy/app/main.py", line 74
Jan 03 18:55:49 raspberrypi python[2447]:     except IOError, e:
Jan 03 18:55:49 raspberrypi python[2447]:                   ^
Jan 03 18:55:49 raspberrypi python[2447]: SyntaxError: invalid syntax

**Comment by Hacksore** [comment]
@kimllee can you please send over a PR?

**Comment by kimllee** [comment]
Hello I have just surrounded the print (line 69) with two appostrophes. :)
