### ISSUE TITLE
raspberry pi zero 2 w + logitech k380

### ISSUE THREAD

**Issue by kimllee** [Hacksore/bt-hid-proxy#3]
Hello,

My logitech keyboard k380 is paired with the pi zero 2 w but I can't use it. How could I make it work please ?

pi@raspberrypi:~ $ sudo systemctl status bt-hid-proxy.service -l && sudo systemctl status usb-gadget.service -l
● bt-hid-proxy.service - BT HID PROXY
     Loaded: loaded (/etc/systemd/system/bt-hid-proxy.service; enabled; vendor preset: enabled)
     Active: activating (start) since Thu 2022-01-20 19:36:36 GMT; 1min 35s ago
   Main PID: 322 (python)
      Tasks: 1 (limit: 409)
        CPU: 814ms
     CGroup: /system.slice/bt-hid-proxy.service
             └─322 /usr/bin/python /home/pi/bt-hid-proxy/app/main.py

Jan 20 19:36:36 raspberrypi systemd[1]: Starting BT HID PROXY...
Jan 20 19:36:38 raspberrypi python[322]: device /dev/input/event0, name "vc4", phys "vc4/input0"

pi@raspberrypi:~ $ sudo systemctl status usb-gadget.service -l
● usb-gadget.service - Create virtual keyboard USB gadget
     Loaded: loaded (/lib/systemd/system/usb-gadget.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Thu 2022-01-20 19:36:37 GMT; 1min 53s ago
    Process: 371 ExecStart=/opt/enable-rpi-hid (code=exited, status=0/SUCCESS)
   Main PID: 371 (code=exited, status=0/SUCCESS)
        CPU: 141ms

Jan 20 19:36:36 raspberrypi systemd[1]: Starting Create virtual keyboard USB gadget...
Jan 20 19:36:37 raspberrypi systemd[1]: usb-gadget.service: Succeeded.
Jan 20 19:36:37 raspberrypi systemd[1]: Finished Create virtual keyboard USB gadget.

pi@raspberrypi:~ $ sudo bluetoothctl
Agent registered
[CHG] Controller B8:27:EB:60:F2:8E Pairable: yes
[CHG] Device F4:73:35:57:9E:EB Connected: yes
[Keyboard K380]# devices
Device F4:73:35:57:9E:EB Keyboard K380
[Keyboard K380]#

**Comment by Hacksore** [comment]
@kimllee What device are you plugging the pi into?

**Comment by kimllee** [comment]
The keyboard works fine with the pi through the GUI of raspberry pi OS. I have tested it with VNC Viewer.
I have reinstalled the os on the pi zero 2 w.

pi@raspberrypi:~ $ pip install evdev
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting evdev
  Downloading https://www.piwheels.org/simple/evdev/evdev-1.4.0-cp39-cp39-linux_armv7l.whl (83 kB)
     |████████████████████████████████| 83 kB 328 kB/s
Installing collected packages: evdev
Successfully installed evdev-1.4.0

pi@raspberrypi:~/bt-hid-proxy $ sudo ./setup.sh
+ set -e
+ set -u
+ grep dtoverlay=dwc2 /boot/config
grep: /boot/config: No such file or directory
+ echo dtoverlay=dwc2
+ grep dwc2 /etc/modules
+ echo dwc2
+ ENABLE_RPI_HID_PATH=/opt/enable-rpi-hid
++ dirname /opt/enable-rpi-hid
+ ENABLE_RPI_HID_DIR=/opt
+ mkdir -p /opt
+ wget https://raw.githubusercontent.com/mtlynch/ansible-role-key-mime-pi/master/files/enable-rpi-hid -O /opt/enable-rpi-hid
--2022-01-21 20:33:02--  https://raw.githubusercontent.com/mtlynch/ansible-role-key-mime-pi/master/files/enable-rpi-hid
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.111.133, 185.199.108.133, 185.199.109.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.111.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 1679 (1.6K) [text/plain]
Saving to: ‘/opt/enable-rpi-hid’

/opt/enable-rpi-hid                                  100%[===================================================================================================================>]   1.64K  --.-KB/s    in 0.001s

2022-01-21 20:33:02 (2.58 MB/s) - ‘/opt/enable-rpi-hid’ saved [1679/1679]

+ chmod +x /opt/enable-rpi-hid
++ mktemp -d
+ cd /tmp/tmp.ixhFdHNRTx
+ wget https://raw.githubusercontent.com/mtlynch/ansible-role-key-mime-pi/master/templates/usb-gadget.systemd.j2
--2022-01-21 20:33:02--  https://raw.githubusercontent.com/mtlynch/ansible-role-key-mime-pi/master/templates/usb-gadget.systemd.j2
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.110.133, 185.199.111.133, 185.199.108.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.110.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 199 [text/plain]
Saving to: ‘usb-gadget.systemd.j2’

usb-gadget.systemd.j2                                100%[===================================================================================================================>]     199  --.-KB/s    in 0s

2022-01-21 20:33:04 (1.09 MB/s) - ‘usb-gadget.systemd.j2’ saved [199/199]

+ sed -e 's@{{ key_mime_pi_initialize_hid_script_path }}@/opt/enable-rpi-hid@g' usb-gadget.systemd.j2
+ systemctl daemon-reload
+ systemctl enable usb-gadget.service
Created symlink /etc/systemd/system/local-fs.target.wants/usb-gadget.service → /lib/systemd/system/usb-gadget.service.
+ sudo cp ./bt-hid-proxy.service /etc/systemd/system
cp: cannot stat './bt-hid-proxy.service': No such file or directory

Nevermind I have set the bt-hid-proxy service manually then I restarted the pi and now I got this.

pi@raspberrypi:~ $ sudo systemctl status bt-hid-proxy.service -l
● bt-hid-proxy.service - BT HID PROXY
     Loaded: loaded (/etc/systemd/system/bt-hid-proxy.service; enabled; vendor preset: enabled)
     Active: activating (auto-restart) (Result: exit-code) since Fri 2022-01-21 20:37:55 CET; 96ms ago
    Process: 1369 ExecStart=/usr/bin/python /home/pi/bt-hid-proxy/app/main.py (code=exited, status=1/FAILURE)
   Main PID: 1369 (code=exited, status=1/FAILURE)
        CPU: 62ms
pi@raspberrypi:~ $ sudo systemctl status usb-gadget.service -l
● usb-gadget.service - Create virtual keyboard USB gadget
     Loaded: loaded (/lib/systemd/system/usb-gadget.service; enabled; vendor preset: enabled)
     Active: inactive (dead) since Fri 2022-01-21 20:36:42 CET; 1min 29s ago
    Process: 364 ExecStart=/opt/enable-rpi-hid (code=exited, status=0/SUCCESS)
   Main PID: 364 (code=exited, status=0/SUCCESS)
        CPU: 134ms

Jan 21 20:36:41 raspberrypi systemd[1]: Starting Create virtual keyboard USB gadget...
Jan 21 20:36:42 raspberrypi systemd[1]: usb-gadget.service: Succeeded.
Jan 21 20:36:42 raspberrypi systemd[1]: Finished Create virtual keyboard USB gadget.

Python2 is used by default on the pi os.
Which version of python is required please ?

The pi is connected to my desktop through the usb port not the power one.

Thank you.

**Comment by kimllee** [comment]
> @kimllee What device are you plugging the pi into?

Logitech keyboard k380

**Comment by Hacksore** [comment]
@kimllee I have used python3 and an apple keyboard.

**Comment by kimllee** [comment]
> @kimllee I have used python3 and an apple keyboard.

Okay since I have changed the python version used by pi OS from 2 to 3 I got this : 

pi@raspberrypi:~ $ sudo systemctl status bt-hid-proxy.service -l
● bt-hid-proxy.service - BT HID PROXY
     Loaded: loaded (/etc/systemd/system/bt-hid-proxy.service; enabled; vendor preset: enabled)
     Active: activating (start) since Thu 2022-01-27 19:07:17 CET; 13s ago
   Main PID: 2918 (python)
      Tasks: 1 (limit: 409)
        CPU: 491ms
     CGroup: /system.slice/bt-hid-proxy.service
             └─2918 /usr/bin/python /home/pi/bt-hid-proxy/app/main.py

Jan 27 19:07:17 raspberrypi systemd[1]: Starting BT HID PROXY...
Jan 27 19:07:17 raspberrypi python[2918]: device /dev/input/event0, name "vc4", phys "vc4/input0"

Looks like it's working better but I can't use my keyboard outside the pi OS gui. What am I missing please ?
Thank you

**Comment by Hacksore** [comment]
@kimllee to be honest I've never tested this with a desktop environment, this very well could be the issue.

Here is how I've used it in the past.
![image](https://user-images.githubusercontent.com/996134/151639762-f6f027a4-5346-4814-a2b7-70c295401aec.png)

**Comment by mohaque0** [comment]
@kimllee I noticed that the rpi only worked when connected to a specific usb port on my computer. Also, the rpi's usb-c port (the same one it usually gets power from) needed to be the port connected to my computer. I haven't experimented so I don't know if other configurations will work too, but maybe running the cable between a different set of ports will help.

**Comment by Hacksore** [comment]
If there is anything codewise to fix this please do raise a PR 🙏.
