### ISSUE TITLE
Error 11 write could not complete without blocking

### ISSUE THREAD

**Issue by mangemayur** [Hacksore/bt-hid-proxy#5]
The code works fine in windows and when i switch OS --- i dont have to reconnect - as the same keyboard works 
but when the machine is booting - and when i want to enter into bios - thats where i get "write could not complete without blocking"

the actual exception is generated from send_keys.... hid_handle.write() method

for me, the actual use case was my bluetooth keyboard should work in bios -- it should help me to enter bios ... but unluckily thats where i am facing above issue .. do let me know if you need any further details to look into it

**Comment by Hacksore** [comment]
I'm curious if this is some kind of [`evdev`](https://github.com/gvalkov/python-evdev) limitation.

It might be worth raising an issue there so they can add any input.

**Comment by mangemayur** [comment]
@Hacksore  Thanks -> i have raise the issue there -> lets see 
I mean What you did is exactly what i was looking for -> but it does not solve my main problem

**Comment by Hacksore** [comment]
Linking it here for reference https://github.com/gvalkov/python-evdev/issues/207

**Comment by Hacksore** [comment]
I guess we are not getting any traction on this upstream but if someone solves this please do raise a PR.
